# Generated by Django 5.1 on 2024-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="data_criacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="data_entrega",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="data_finalizacao",
            field=models.DateField(null=True),
        ),
    ]
